const HIGH_RISK_DIRS = [
  "node_modules",
  ".next",
  "dist",
  "build",
  "coverage",
  ".turbo",
  ".venv",
  "venv",
  "__pycache__",
  ".pytest_cache",
  ".cache",
  "logs",
  "test-results",
  "playwright-report",
  "tmp",
  "temp",
];

const HIGH_RISK_FILE_NAMES = new Set([
  "package-lock.json",
  "yarn.lock",
  "pnpm-lock.yaml",
  "npm-shrinkwrap.json",
  "coverage-final.json",
]);

const BINARY_EXTENSIONS = new Set([
  ".png",
  ".jpg",
  ".jpeg",
  ".gif",
  ".webp",
  ".ico",
  ".svg",
  ".pdf",
  ".zip",
  ".gz",
  ".tar",
  ".tgz",
  ".mp4",
  ".mov",
  ".mp3",
  ".wav",
  ".woff",
  ".woff2",
  ".ttf",
  ".otf",
  ".pyc",
  ".class",
  ".wasm",
  ".sqlite",
  ".sqlite3",
  ".db",
  ".bin",
]);

const SOURCE_EXTENSIONS = new Set([
  ".js",
  ".jsx",
  ".ts",
  ".tsx",
  ".py",
  ".go",
  ".rs",
  ".java",
  ".c",
  ".cc",
  ".cpp",
  ".h",
  ".hpp",
  ".cs",
  ".rb",
  ".php",
  ".swift",
  ".kt",
  ".m",
  ".mm",
  ".scala",
  ".sh",
  ".sql",
  ".css",
  ".scss",
  ".html",
  ".vue",
  ".svelte",
]);

const INSTRUCTION_FILES = [
  "CLAUDE.md",
  "AGENTS.md",
  "README.md",
  "README",
  ".openai/instructions.md",
  ".codex/AGENTS.md",
  ".codex/instructions.md",
  ".codex/config.toml",
];

const DEFAULT_CLAUDEIGNORE = [
  "node_modules/",
  ".next/",
  "dist/",
  "build/",
  "coverage/",
  ".turbo/",
  ".venv/",
  "venv/",
  "__pycache__/",
  "pycache/",
  ".pytest_cache/",
  ".cache/",
  "logs/",
  "*.log",
  "*.lock",
  "*.tmp",
  "*.min.js",
  "*.min.css",
  "coverage-final.json",
  "package-lock.json",
  "yarn.lock",
  "pnpm-lock.yaml",
  "test-results/",
  "playwright-report/",
];

const NPX_COMMAND = "npx getprismo";
const DEFAULT_PRISMO_PROXY_URL = process.env.PRISMO_PROXY_URL || "http://localhost:8000";
const CLAUDE_PRICING = {
  "opus-4.1": { name: "Claude Opus 4.1", input: 15, output: 75, cacheWrite: 18.75, cacheRead: 1.5 },
  "opus-4": { name: "Claude Opus 4", input: 15, output: 75, cacheWrite: 18.75, cacheRead: 1.5 },
  "sonnet-4": { name: "Claude Sonnet 4", input: 3, output: 15, cacheWrite: 3.75, cacheRead: 0.3 },
  "sonnet-3.7": { name: "Claude Sonnet 3.7", input: 3, output: 15, cacheWrite: 3.75, cacheRead: 0.3 },
  "sonnet-3.5": { name: "Claude Sonnet 3.5", input: 3, output: 15, cacheWrite: 3.75, cacheRead: 0.3 },
  "haiku-3.5": { name: "Claude Haiku 3.5", input: 0.8, output: 4, cacheWrite: 1, cacheRead: 0.08 },
  "opus-3": { name: "Claude Opus 3", input: 15, output: 75, cacheWrite: 18.75, cacheRead: 1.5 },
  "haiku-3": { name: "Claude Haiku 3", input: 0.25, output: 1.25, cacheWrite: 0.3, cacheRead: 0.03 },
};
const DEFAULT_CLAUDE_PRICING_KEY = "sonnet-4";
const GENERATED_ARTIFACT_PATTERNS = [
  /(^|\/)node_modules\//,
  /(^|\/)\.next\//,
  /(^|\/)dist\//,
  /(^|\/)build\//,
  /(^|\/)coverage\//,
  /(^|\/)playwright-report\//,
  /(^|\/)test-results\//,
  /(^|\/)__pycache__\//,
  /(^|\/)\.pytest_cache\//,
  /(^|\/)\.cache\//,
  /(^|\/)logs?\//,
  /package-lock\.json$/,
  /pnpm-lock\.yaml$/,
  /yarn\.lock$/,
  /coverage-final\.json$/,
  /\.min\.(js|css)$/,
  /(^|\/)assets\/[^/]+-[A-Za-z0-9_-]{6,}\.(js|css|map)$/,
];


module.exports = {
  HIGH_RISK_DIRS,
  HIGH_RISK_FILE_NAMES,
  BINARY_EXTENSIONS,
  SOURCE_EXTENSIONS,
  INSTRUCTION_FILES,
  DEFAULT_CLAUDEIGNORE,
  NPX_COMMAND,
  DEFAULT_PRISMO_PROXY_URL,
  CLAUDE_PRICING,
  DEFAULT_CLAUDE_PRICING_KEY,
  GENERATED_ARTIFACT_PATTERNS,
};
